-- === TABLAS COMPLETAS CON LOS NUEVOS CAMPOS ===
-- Cópialo y pégalo en el SQL editor de Supabase.

-- 1. Tabla de CLIENTES
CREATE TABLE IF NOT EXISTS cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL,
    correo TEXT,
    telefono TEXT,
    celular TEXT,
    rfc TEXT,
    direccion TEXT,
    time TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabla de VEHÍCULOS
CREATE TABLE IF NOT EXISTS vehiculos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    marca TEXT,
    modelo TEXT,
    tipo_vehiculo TEXT,
    version TEXT,
    serie TEXT,
    servicio TEXT,
    puertas TEXT,
    paquete TEXT,
    fronterizo_modelo TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabla de PÓLIZAS
CREATE TABLE IF NOT EXISTS poliza (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES cliente(id) ON DELETE CASCADE,
    vehiculo_id BIGINT REFERENCES vehiculos(id) ON DELETE CASCADE,
    aseguradora TEXT,
    numero_poliza TEXT,
    inicio DATE,
    fin DATE,
    forma_pago TEXT,
    prima_neta DECIMAL(12,2),
    prima_total DECIMAL(12,2),
    estado TEXT,
    agente TEXT,
    conducto TEXT,
    tarifa TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- === SEGURIDAD Y POLÍTICAS DE AUTENTICACIÓN (RLS) ===
-- Ejecuta esto de inmediato para proteger las tablas de anónimos y evitar el error 42501.

-- Habilitar RLS en las 3 tablas
ALTER TABLE cliente ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehiculos ENABLE ROW LEVEL SECURITY;
ALTER TABLE poliza ENABLE ROW LEVEL SECURITY;

-- Crear políticas para permitir full access SOLO a los usuarios logueados por GOOGLE en Supabase Auth
CREATE POLICY "Logueados pueden ver y cambiar clientes" ON cliente FOR ALL TO authenticated USING (true);
CREATE POLICY "Logueados pueden ver y cambiar vehículos" ON vehiculos FOR ALL TO authenticated USING (true);
CREATE POLICY "Logueados pueden ver y cambiar pólizas" ON poliza FOR ALL TO authenticated USING (true);
