const t = "212546777   AMPLIA DANIELA CAROLINA AGUILAR PEREZ STA ELENA EXT. 7 INT. A   22170 SANTA ELENA   6641234566";
let mTab = t.match(/(AMPLIA|LIMITADA|COBERTURA AMPLIA|PAQUETE)\s+([A-ZÁÉÍÓÚÑ\s]+?)(?=\s+(?:EXT|INT|CALLE|AVE|BLVD|STA|SAN|COLONIA|C\.|R\.|#|\d{2,}))/i);
console.log(mTab);
